# This is a basic workflow to help you get started with Actions

name: Okteto Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Okteto Login
        uses: okteto/login@latest
        with:
          # Your okteto API token
          token: ${{ secrets.OKTETO_TOKEN }}
      
      
      - name: Okteto Pipeline
        uses: okteto/pipeline@latest
        with:
          # The name of the pipeline
          name: contacts-fis2019-auto
          namespace: resinas
    
